-- Everyday Pulse 96-pulse setup.
-- Run this whole file in Supabase SQL Editor.
-- It adds the required columns, seeds 96 active pulses, then verifies the count.

-- Run this first.
alter table public.missions
  add column if not exists mission_id_slug text,
  add column if not exists mission text,
  add column if not exists reflection_prompt text,
  add column if not exists mission_path text;

create unique index if not exists missions_mission_id_slug_idx
on public.missions (mission_id_slug);


-- Run after 003a_pulse_columns.sql. Part 1 of 4.
insert into public.missions (
  mission_id_slug,
  title,
  mission,
  world,
  category,
  difficulty,
  xp,
  time_required,
  mission_path,
  tags,
  pack,
  unlock_xp,
  why_it_matters,
  completion_condition,
  reflection_prompt,
  safety_note,
  is_sensitive,
  is_active
)
values
  ('i_want_to_feel_lighter_i_only_have_5_minutes_1_do_a_one_song_mood_shift', 'Do a One-Song Mood Shift', 'Play one upbeat song and move, tidy, stretch, or dance for the full track without checking your phone.', 'Recharge', 'Fun Fuel', 'Easy', 10, 'I only have 5 minutes', 'I want to feel lighter', array['quick', 'easy', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'Light movement can interrupt a heavy mood before it turns into a whole day.', 'You move for one full song without touching your phone.', 'What changed in your mood after one song?', null, false, true),
  ('i_want_to_feel_lighter_i_only_have_5_minutes_2_clear_one_tiny_annoyance', 'Clear One Tiny Annoyance', 'Fix one tiny thing that has been irritating you: refill something, throw away trash, untangle a cable, or put one item back.', 'Recharge', 'Fun Fuel', 'Easy', 10, 'I only have 5 minutes', 'I want to feel lighter', array['quick', 'easy', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'Small annoyances quietly drain energy. Removing one gives you a fast sense of relief.', 'One tiny irritation is handled.', 'Which tiny annoyance was taking more space than it deserved?', null, false, true),
  ('i_want_to_feel_lighter_i_only_have_5_minutes_3_send_a_light_message', 'Send a Light Message', 'Send one low-pressure funny, warm, or playful message to someone who would enjoy it.', 'Recharge', 'Fun Fuel', 'Easy', 10, 'I only have 5 minutes', 'I want to feel lighter', array['quick', 'easy', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'A light moment with another person can loosen the grip of a serious day.', 'You send one warm or playful message.', 'Who felt easy to share a lighter moment with?', null, false, true),
  ('i_want_to_feel_lighter_i_have_10_15_minutes_1_make_a_tiny_joy_list', 'Make a Tiny Joy List', 'Write down ten small things that reliably make your day feel lighter, then do or schedule one of them.', 'Recharge', 'Fun Fuel', 'Easy', 10, 'I have 10-15 minutes', 'I want to feel lighter', array['short', 'doable', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'Joy becomes easier to choose when you know what actually works for you.', 'You list ten tiny joy cues and act on or schedule one.', 'Which small joy felt easiest to choose today?', null, false, true),
  ('i_want_to_feel_lighter_i_have_10_15_minutes_2_book_a_real_fun_slot', 'Book a Real Fun Slot', 'Choose one fun activity and make it real by adding a date, time, invitation, booking, or physical setup.', 'Recharge', 'Fun Fuel', 'Easy', 10, 'I have 10-15 minutes', 'I want to feel lighter', array['short', 'doable', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'Fun is easier to protect when it has a real commitment or cue attached.', 'One fun activity has a date, trigger, invitation, booking, or setup.', 'What kind of fun have you been postponing?', null, false, true),
  ('i_want_to_feel_lighter_i_have_10_15_minutes_3_make_your_space_smile', 'Make Your Space Smile', 'Add one small pleasant detail to your space: open a curtain, play music, light a candle, place a photo, or move one object.', 'Recharge', 'Fun Fuel', 'Easy', 10, 'I have 10-15 minutes', 'I want to feel lighter', array['short', 'doable', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'Your environment can quietly remind your body that the day is not only work.', 'One visible detail in your space feels more pleasant than before.', 'What small detail changed the room''s mood?', null, false, true),
  ('i_want_to_feel_lighter_i_have_15_30_minutes_1_take_a_treat_errand', 'Take a Treat Errand', 'Walk or go out for one small treat or pleasant practical errand, and keep your phone away except for essentials.', 'Recharge', 'Fun Fuel', 'Medium', 25, 'I have 15-30 minutes', 'I want to feel lighter', array['doable', 'focus', 'meaningful', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'A tiny outing can make the day feel less trapped inside your head.', 'You complete one pleasant errand or treat run with minimal scrolling.', 'What felt different once you left your usual loop?', null, false, true),
  ('i_want_to_feel_lighter_i_have_15_30_minutes_2_refresh_a_small_corner', 'Refresh a Small Corner', 'Pick one small corner and make it more pleasant by clearing, wiping, rearranging, and adding one nice detail.', 'Recharge', 'Fun Fuel', 'Medium', 25, 'I have 15-30 minutes', 'I want to feel lighter', array['doable', 'focus', 'meaningful', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'A refreshed corner gives your brain visible proof that the day can shift.', 'One corner is cleaner and more pleasant than when you started.', 'What did the corner feel like before and after?', null, false, true),
  ('i_want_to_feel_lighter_i_have_15_30_minutes_3_create_a_mini_reward_plan', 'Create a Mini Reward Plan', 'Choose one task you have been avoiding and attach a simple reward you will take immediately after doing it.', 'Recharge', 'Fun Fuel', 'Medium', 25, 'I have 15-30 minutes', 'I want to feel lighter', array['doable', 'focus', 'meaningful', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'Rewards make effort feel less endless and help your brain start moving.', 'One avoided task has a clear reward attached and scheduled.', 'What reward would actually make effort feel lighter?', null, false, true),
  ('i_want_to_feel_lighter_i_have_more_than_30_minutes_1_do_a_joy_walk', 'Do a Joy Walk', 'Take a 30-minute walk with the goal of noticing, photographing, or collecting five things that feel pleasant.', 'Recharge', 'Fun Fuel', 'Hard', 50, 'I have more than 30 minutes', 'I want to feel lighter', array['deep', 'purpose', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'Looking for small good things trains attention away from the same old weight.', 'You complete a walk and capture five pleasant details.', 'Which detail surprised you most?', null, false, true),
  ('i_want_to_feel_lighter_i_have_more_than_30_minutes_2_give_a_hobby_one_full_block', 'Give a Hobby One Full Block', 'Spend 45 minutes on a hobby with no productivity goal: play, cook, read, make, garden, sing, or learn for enjoyment.', 'Recharge', 'Fun Fuel', 'Hard', 50, 'I have more than 30 minutes', 'I want to feel lighter', array['deep', 'purpose', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'Pleasure gets squeezed out when every activity has to prove its usefulness.', 'You spend one uninterrupted block on a hobby for its own sake.', 'What felt good once usefulness was not the point?', null, false, true),
  ('i_want_to_feel_lighter_i_have_more_than_30_minutes_3_plan_a_low_pressure_hangout', 'Plan a Low-Pressure Hangout', 'Set up one low-pressure hangout, call, game, walk, or meal with someone you enjoy being around.', 'Recharge', 'Fun Fuel', 'Hard', 50, 'I have more than 30 minutes', 'I want to feel lighter', array['deep', 'purpose', 'fun', 'joy', 'play']::text[], 'Starter', 0, 'Shared ease can be one of the fastest ways to feel lighter.', 'One low-pressure plan is proposed, scheduled, or confirmed.', 'Who makes life feel a little less heavy?', null, false, true),
  ('i_want_to_slow_down_i_only_have_5_minutes_1_make_a_quiet_drink_pause', 'Make a Quiet Drink Pause', 'Make water, tea, coffee, or another drink and take the first five sips without a screen.', 'Recharge', 'Refuel', 'Easy', 10, 'I only have 5 minutes', 'I want to slow down', array['quick', 'easy', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'A small pause teaches your nervous system that not every minute needs input.', 'You take five slow sips without looking at a screen.', 'What did you notice when nothing else was happening?', null, false, true),
  ('i_want_to_slow_down_i_only_have_5_minutes_2_write_the_load_down', 'Write the Load Down', 'Write every open worry, task, or loop in your head for five minutes without solving anything.', 'Recharge', 'Refuel', 'Easy', 10, 'I only have 5 minutes', 'I want to slow down', array['quick', 'easy', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'The mind slows down when it stops having to hold everything at once.', 'You capture the mental load on paper or in a note.', 'Which thought kept repeating most loudly?', null, false, true),
  ('i_want_to_slow_down_i_only_have_5_minutes_3_do_the_slow_exhale_reset', 'Do the Slow Exhale Reset', 'Take ten slow breaths with longer exhales, then name one thing that can wait.', 'Recharge', 'Refuel', 'Easy', 10, 'I only have 5 minutes', 'I want to slow down', array['quick', 'easy', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'Slowing the body first can soften urgency in the mind.', 'You take ten slow breaths and name one thing that can wait.', 'What felt less urgent after breathing?', null, false, true),
  ('i_want_to_slow_down_i_have_10_15_minutes_1_build_tonight_s_phone_landing_zone', 'Build Tonight''s Phone Landing Zone', 'Choose a charging spot away from bed, place one offline wind-down item beside your bed, and set your phone there tonight.', 'Recharge', 'Refuel', 'Easy', 10, 'I have 10-15 minutes', 'I want to slow down', array['short', 'doable', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'A prepared environment makes it easier to rest without negotiating later.', 'Your phone landing zone is chosen and one offline item is ready.', 'What usually pulls you back to your phone at night?', null, false, true),
  ('i_want_to_slow_down_i_have_10_15_minutes_2_do_a_gentle_stretch_scan', 'Do a Gentle Stretch Scan', 'Spend ten minutes stretching slowly from neck to feet, pausing wherever your body feels tight.', 'Recharge', 'Refuel', 'Easy', 10, 'I have 10-15 minutes', 'I want to slow down', array['short', 'doable', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'Slow movement can bring your attention back into your body without demanding intensity.', 'You complete a slow ten-minute stretch or mobility scan.', 'Where did your body ask for more patience?', null, false, true),
  ('i_want_to_slow_down_i_have_10_15_minutes_3_choose_one_thing_to_postpone', 'Choose One Thing to Postpone', 'Look at your list and deliberately move one non-urgent task to another day or remove it completely.', 'Recharge', 'Refuel', 'Easy', 10, 'I have 10-15 minutes', 'I want to slow down', array['short', 'doable', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'Slowing down sometimes means deciding what does not need today''s energy.', 'One non-urgent task is postponed, removed, or delegated.', 'What became lighter when you let one thing wait?', null, false, true),
  ('i_want_to_slow_down_i_have_15_30_minutes_1_take_a_no_input_walk', 'Take a No-Input Walk', 'Walk for 20 minutes without music, podcasts, calls, or scrolling.', 'Recharge', 'Refuel', 'Medium', 25, 'I have 15-30 minutes', 'I want to slow down', array['doable', 'focus', 'meaningful', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'Silence gives your thoughts room to settle instead of being constantly replaced.', 'You complete a no-input walk.', 'What surfaced once there was no input?', null, false, true),
  ('i_want_to_slow_down_i_have_15_30_minutes_2_make_a_slow_meal_setup', 'Make a Slow Meal Setup', 'Prepare one simple snack or meal component slowly: wash fruit, cut vegetables, cook eggs, or set up breakfast.', 'Recharge', 'Refuel', 'Medium', 25, 'I have 15-30 minutes', 'I want to slow down', array['doable', 'focus', 'meaningful', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'Basic care feels different when it is not rushed like another task.', 'One simple food or drink setup is ready.', 'What changed when you moved at a slower pace?', null, false, true),
  ('i_want_to_slow_down_i_have_15_30_minutes_3_close_three_open_loops', 'Close Three Open Loops', 'Pick three small open loops and close them: reply, file, delete, put away, pay, schedule, or decide.', 'Recharge', 'Refuel', 'Medium', 25, 'I have 15-30 minutes', 'I want to slow down', array['doable', 'focus', 'meaningful', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'Open loops create background noise. Closing a few helps your mind settle.', 'Three small open loops are closed or clearly decided.', 'Which loop had been stealing the most attention?', null, false, true),
  ('i_want_to_slow_down_i_have_more_than_30_minutes_1_create_a_screen_free_evening_block', 'Create a Screen-Free Evening Block', 'Choose a 60-minute screen-free block tonight and prepare what you will do instead: book, walk, bath, call, cooking, or music.', 'Recharge', 'Refuel', 'Hard', 50, 'I have more than 30 minutes', 'I want to slow down', array['deep', 'purpose', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'Rest needs a plan when screens are the default.', 'A 60-minute screen-free block is scheduled and prepared.', 'What would make tonight feel more restful?', null, false, true),
  ('i_want_to_slow_down_i_have_more_than_30_minutes_2_do_a_gentle_room_reset', 'Do a Gentle Room Reset', 'Reset one room slowly: clear surfaces, put things back, wipe one area, and make the room easier to enter.', 'Recharge', 'Refuel', 'Hard', 50, 'I have more than 30 minutes', 'I want to slow down', array['deep', 'purpose', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'A calmer room gives your body a quieter place to land.', 'One room feels visibly calmer and easier to use.', 'What changed in your body when the room changed?', null, false, true),
  ('i_want_to_slow_down_i_have_more_than_30_minutes_3_take_a_slow_admin_hour', 'Take a Slow Admin Hour', 'Spend 45 minutes handling life admin at a calm pace: bills, forms, appointments, files, or messages, with one break in the middle.', 'Recharge', 'Refuel', 'Hard', 50, 'I have more than 30 minutes', 'I want to slow down', array['deep', 'purpose', 'calm', 'mindful', 'rest']::text[], 'Starter', 0, 'Admin feels less threatening when it is contained and paced.', 'One calm admin block is completed with visible progress.', 'What felt more manageable after giving it time?', null, false, true)

on conflict (mission_id_slug) do update set
  title = excluded.title,
  mission = excluded.mission,
  world = excluded.world,
  category = excluded.category,
  difficulty = excluded.difficulty,
  xp = excluded.xp,
  time_required = excluded.time_required,
  mission_path = excluded.mission_path,
  tags = excluded.tags,
  pack = excluded.pack,
  unlock_xp = excluded.unlock_xp,
  why_it_matters = excluded.why_it_matters,
  completion_condition = excluded.completion_condition,
  reflection_prompt = excluded.reflection_prompt,
  safety_note = excluded.safety_note,
  is_sensitive = excluded.is_sensitive,
  is_active = excluded.is_active;


-- Run after 003a_pulse_columns.sql. Part 2 of 4.
insert into public.missions (
  mission_id_slug,
  title,
  mission,
  world,
  category,
  difficulty,
  xp,
  time_required,
  mission_path,
  tags,
  pack,
  unlock_xp,
  why_it_matters,
  completion_condition,
  reflection_prompt,
  safety_note,
  is_sensitive,
  is_active
)
values
  ('i_want_to_do_something_meaningful_i_only_have_5_minutes_1_choose_today_s_one_value', 'Choose Today''s One Value', 'Pick one value you want today to show and write one small action that would prove it.', 'Reflect', 'North Star', 'Easy', 10, 'I only have 5 minutes', 'I want to do something meaningful', array['quick', 'easy', 'deep', 'reflection', 'purpose']::text[], 'Starter', 0, 'A value becomes useful when it points to a real action.', 'You choose one value and one proof action for today.', 'What value would make today feel worthwhile?', null, false, true),
  ('i_want_to_do_something_meaningful_i_only_have_5_minutes_2_repair_one_tiny_promise', 'Repair One Tiny Promise', 'Find one small promise, reply, or intention you left hanging and take the smallest next step on it.', 'Reflect', 'North Star', 'Easy', 10, 'I only have 5 minutes', 'I want to do something meaningful', array['quick', 'easy', 'deep', 'reflection', 'purpose']::text[], 'Starter', 0, 'Meaning often returns when your actions line up with your word.', 'You take one next step on a small unfinished promise.', 'What promise still mattered to you?', null, false, true),
  ('i_want_to_do_something_meaningful_i_only_have_5_minutes_3_write_a_five_line_truth', 'Write a Five-Line Truth', 'Write five honest lines about what matters right now, then underline the sentence that feels most true.', 'Reflect', 'North Star', 'Easy', 10, 'I only have 5 minutes', 'I want to do something meaningful', array['quick', 'easy', 'deep', 'reflection', 'purpose']::text[], 'Starter', 0, 'Meaning gets clearer when vague feelings become words.', 'You write five honest lines and underline one true sentence.', 'Which sentence felt most alive?', null, false, true),
  ('i_want_to_do_something_meaningful_i_have_10_15_minutes_1_block_one_value_proof_action', 'Block One Value-Proof Action', 'Choose one value for this week and block one 15-minute action on your calendar that would prove it in real life.', 'Reflect', 'North Star', 'Easy', 10, 'I have 10-15 minutes', 'I want to do something meaningful', array['short', 'doable', 'deep', 'reflection', 'purpose']::text[], 'Starter', 0, 'Values become easier to live when they have a time, place, and action attached.', 'One value-proof action is scheduled.', 'What value do you want your week to show?', null, false, true),
  ('i_want_to_do_something_meaningful_i_have_10_15_minutes_2_send_one_earned_appreciation', 'Send One Earned Appreciation', 'Message someone whose effort shaped you and tell them one specific way it mattered.', 'Reflect', 'North Star', 'Easy', 10, 'I have 10-15 minutes', 'I want to do something meaningful', array['short', 'doable', 'deep', 'reflection', 'purpose']::text[], 'Starter', 0, 'Meaning deepens when appreciation becomes specific and shared.', 'You send one specific appreciation message.', 'What did this person help make possible?', null, false, true),
  ('i_want_to_do_something_meaningful_i_have_10_15_minutes_3_choose_a_small_contribution', 'Choose a Small Contribution', 'Choose one small contribution you can make today: help, teach, donate, share, clean, support, or encourage, then start it.', 'Reflect', 'North Star', 'Easy', 10, 'I have 10-15 minutes', 'I want to do something meaningful', array['short', 'doable', 'deep', 'reflection', 'purpose']::text[], 'Starter', 0, 'Contribution turns private intention into real-world evidence.', 'One small contribution is chosen and started.', 'What kind of contribution feels honest, not performative?', null, false, true),
  ('i_want_to_do_something_meaningful_i_have_15_30_minutes_1_do_a_values_audit', 'Do a Values Audit', 'Look at yesterday or last week and mark three actions that matched your values and one action you want to adjust.', 'Reflect', 'North Star', 'Medium', 25, 'I have 15-30 minutes', 'I want to do something meaningful', array['doable', 'focus', 'meaningful', 'deep', 'reflection', 'purpose']::text[], 'Starter', 0, 'A quick audit helps you steer without shaming yourself.', 'Three aligned actions and one adjustment are written down.', 'What pattern do you want to continue?', null, false, true),
  ('i_want_to_do_something_meaningful_i_have_15_30_minutes_2_move_a_meaningful_project_forward', 'Move a Meaningful Project Forward', 'Spend 25 minutes on one project, relationship, skill, or responsibility that still matters six months from now.', 'Reflect', 'North Star', 'Medium', 25, 'I have 15-30 minutes', 'I want to do something meaningful', array['doable', 'focus', 'meaningful', 'deep', 'reflection', 'purpose']::text[], 'Starter', 0, 'Meaningful work often needs protected attention more than motivation.', 'You complete 25 minutes of progress on something that matters long term.', 'Why does this still matter six months from now?', null, false, true),
  ('i_want_to_do_something_meaningful_i_have_15_30_minutes_3_make_one_life_easier_for_someone', 'Make One Life Easier for Someone', 'Do one practical task that genuinely makes another person''s day easier: arrange, clean, share, prepare, fix, or follow up.', 'Reflect', 'North Star', 'Medium', 25, 'I have 15-30 minutes', 'I want to do something meaningful', array['doable', 'focus', 'meaningful', 'deep', 'reflection', 'purpose']::text[], 'Starter', 0, 'Meaning can be simple when it reduces someone else''s load.', 'One practical helpful action is completed.', 'Whose load became a little lighter?', null, false, true),
  ('i_want_to_do_something_meaningful_i_have_more_than_30_minutes_1_design_a_seven_day_proof', 'Design a Seven-Day Proof', 'Choose one value and design a seven-day proof: one small daily action, when it happens, and how you will track it.', 'Reflect', 'North Star', 'Hard', 50, 'I have more than 30 minutes', 'I want to do something meaningful', array['deep', 'purpose', 'reflection']::text[], 'Starter', 0, 'A week of small proof turns meaning into lived behavior.', 'A seven-day value proof is written and scheduled.', 'What value deserves a week of evidence?', null, false, true),
  ('i_want_to_do_something_meaningful_i_have_more_than_30_minutes_2_finish_a_meaningful_loose_end', 'Finish a Meaningful Loose End', 'Pick one unfinished meaningful task and give it a full 45-minute block: letter, application, repair, plan, form, or project step.', 'Reflect', 'North Star', 'Hard', 50, 'I have more than 30 minutes', 'I want to do something meaningful', array['deep', 'purpose', 'reflection']::text[], 'Starter', 0, 'Loose ends that matter can quietly weigh on your identity.', 'One meaningful loose end has visible progress or closure.', 'What did finishing or moving this forward restore?', null, false, true),
  ('i_want_to_do_something_meaningful_i_have_more_than_30_minutes_3_create_a_personal_north_star_page', 'Create a Personal North Star Page', 'Write one page with what matters now, what you are no longer available for, and one action for the next 24 hours.', 'Reflect', 'North Star', 'Hard', 50, 'I have more than 30 minutes', 'I want to do something meaningful', array['deep', 'purpose', 'reflection']::text[], 'Starter', 0, 'A clear page can become a compass when everything feels equally loud.', 'One North Star page is written with a next action.', 'What are you ready to stop pretending is neutral?', null, false, true),
  ('i_want_a_small_courage_boost_i_only_have_5_minutes_1_ask_one_clear_question', 'Ask One Clear Question', 'Ask one question you have been avoiding because you did not want to look awkward, needy, or behind.', 'Connect', 'Tiny Dares', 'Easy', 10, 'I only have 5 minutes', 'I want a small courage boost', array['quick', 'easy', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Small courage grows when you let yourself need clarity.', 'You ask one clear question.', 'What made this question feel harder than it was?', 'Only do this if it feels safe and appropriate. A smaller version counts.', true, true),
  ('i_want_a_small_courage_boost_i_only_have_5_minutes_2_make_one_small_request', 'Make One Small Request', 'Ask for one small thing directly: a time, answer, favor, edit, introduction, price, or clarification.', 'Connect', 'Tiny Dares', 'Easy', 10, 'I only have 5 minutes', 'I want a small courage boost', array['quick', 'easy', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Direct requests train confidence without requiring a dramatic leap.', 'You make one clear, respectful request.', 'What did you learn by asking directly?', 'Only do this if it feels safe and appropriate. A smaller version counts.', true, true),
  ('i_want_a_small_courage_boost_i_only_have_5_minutes_3_use_your_real_voice', 'Use Your Real Voice', 'Send one voice note or say one sentence out loud that you would normally over-edit in text.', 'Connect', 'Tiny Dares', 'Easy', 10, 'I only have 5 minutes', 'I want a small courage boost', array['quick', 'easy', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Courage can be as small as letting your real voice take up space.', 'You send or speak one honest sentence.', 'What did your voice carry that text would hide?', null, false, true),
  ('i_want_a_small_courage_boost_i_have_10_15_minutes_1_ask_for_useful_feedback', 'Ask for Useful Feedback', 'Send one piece of work, idea, or plan to a safe person and ask one specific feedback question.', 'Connect', 'Tiny Dares', 'Easy', 10, 'I have 10-15 minutes', 'I want a small courage boost', array['short', 'doable', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Specific feedback makes improvement less scary than vague judgment.', 'You ask one safe person for one specific piece of feedback.', 'What feedback question felt most useful?', null, false, true),
  ('i_want_a_small_courage_boost_i_have_10_15_minutes_2_send_the_simple_invite', 'Send the Simple Invite', 'Invite someone to a walk, coffee, call, co-working block, or casual plan without overexplaining.', 'Connect', 'Tiny Dares', 'Easy', 10, 'I have 10-15 minutes', 'I want a small courage boost', array['short', 'doable', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Connection often needs one brave sentence, not a perfect plan.', 'You send one simple invitation.', 'What did you want to control before sending it?', null, false, true),
  ('i_want_a_small_courage_boost_i_have_10_15_minutes_3_move_one_draft_forward', 'Move One Draft Forward', 'Take one private draft and move it to the next step: outline, edit, send, upload, schedule, or request review.', 'Connect', 'Tiny Dares', 'Easy', 10, 'I have 10-15 minutes', 'I want a small courage boost', array['short', 'doable', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'A draft becomes less scary when it moves one step forward.', 'One draft moves to a real next step.', 'What did this draft need more than perfection?', null, false, true),
  ('i_want_a_small_courage_boost_i_have_15_30_minutes_1_make_the_avoided_call', 'Make the Avoided Call', 'Make one practical call or send one serious message you have been delaying: appointment, repair, bill, booking, or follow-up.', 'Connect', 'Tiny Dares', 'Medium', 25, 'I have 15-30 minutes', 'I want a small courage boost', array['doable', 'focus', 'meaningful', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Avoided practical conversations grow heavier the longer they wait.', 'One delayed call or serious message is completed.', 'What did you expect to happen, and what actually happened?', null, false, true),
  ('i_want_a_small_courage_boost_i_have_15_30_minutes_2_publish_a_small_opinion', 'Publish a Small Opinion', 'Share one honest, respectful opinion, recommendation, or lesson in a post, message, review, meeting, or group.', 'Connect', 'Tiny Dares', 'Medium', 25, 'I have 15-30 minutes', 'I want a small courage boost', array['doable', 'focus', 'meaningful', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Courage grows when your point of view becomes visible in a low-stakes way.', 'You share one honest opinion or lesson where someone can see it.', 'What part of being visible felt uncomfortable?', null, false, true),
  ('i_want_a_small_courage_boost_i_have_15_30_minutes_3_apply_to_one_opportunity', 'Apply to One Opportunity', 'Apply, submit interest, or send a first message for one opportunity that is slightly outside your comfort zone.', 'Connect', 'Tiny Dares', 'Medium', 25, 'I have 15-30 minutes', 'I want a small courage boost', array['doable', 'focus', 'meaningful', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Trying creates more possibility than waiting until you feel fully ready.', 'One application, interest form, or first message is sent.', 'What story did you have to ignore to apply?', null, false, true),
  ('i_want_a_small_courage_boost_i_have_more_than_30_minutes_1_attend_the_first_session', 'Attend the First Session', 'Attend or register for one class, event, group, workshop, or session you have been curious about.', 'Connect', 'Tiny Dares', 'Hard', 50, 'I have more than 30 minutes', 'I want a small courage boost', array['deep', 'purpose', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Showing up once is often the hardest courage rep.', 'You attend, register, or put the first session on your calendar.', 'What part of showing up felt like a stretch?', null, false, true),
  ('i_want_a_small_courage_boost_i_have_more_than_30_minutes_2_prepare_the_hard_conversation', 'Prepare the Hard Conversation', 'Write the point of one hard conversation, what you need to say, and one calm opening sentence.', 'Connect', 'Tiny Dares', 'Hard', 50, 'I have more than 30 minutes', 'I want a small courage boost', array['deep', 'purpose', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'Preparation lowers the chance that courage turns into panic or avoidance.', 'You write a calm opening and the main point you need to say.', 'What do you want to be honest about without being harsh?', 'Only do this if it feels safe and appropriate. A smaller version counts.', true, true),
  ('i_want_a_small_courage_boost_i_have_more_than_30_minutes_3_pitch_one_real_thing', 'Pitch One Real Thing', 'Create and send a simple pitch for one real thing: service, collaboration, project, idea, sale, or request for help.', 'Connect', 'Tiny Dares', 'Hard', 50, 'I have more than 30 minutes', 'I want a small courage boost', array['deep', 'purpose', 'brave', 'confidence', 'discomfort']::text[], 'Starter', 0, 'A pitch turns hidden ambition into a real-world attempt.', 'One simple pitch is written and sent or scheduled.', 'What are you asking the world to take seriously?', null, false, true)

on conflict (mission_id_slug) do update set
  title = excluded.title,
  mission = excluded.mission,
  world = excluded.world,
  category = excluded.category,
  difficulty = excluded.difficulty,
  xp = excluded.xp,
  time_required = excluded.time_required,
  mission_path = excluded.mission_path,
  tags = excluded.tags,
  pack = excluded.pack,
  unlock_xp = excluded.unlock_xp,
  why_it_matters = excluded.why_it_matters,
  completion_condition = excluded.completion_condition,
  reflection_prompt = excluded.reflection_prompt,
  safety_note = excluded.safety_note,
  is_sensitive = excluded.is_sensitive,
  is_active = excluded.is_active;


-- Run after 003a_pulse_columns.sql. Part 3 of 4.
insert into public.missions (
  mission_id_slug,
  title,
  mission,
  world,
  category,
  difficulty,
  xp,
  time_required,
  mission_path,
  tags,
  pack,
  unlock_xp,
  why_it_matters,
  completion_condition,
  reflection_prompt,
  safety_note,
  is_sensitive,
  is_active
)
values
  ('i_want_to_do_something_kind_i_only_have_5_minutes_1_send_a_specific_thank_you', 'Send a Specific Thank-You', 'Send one message thanking someone for a specific effort, favor, lesson, introduction, or moment they may not know mattered.', 'Connect', 'Good Sparks', 'Easy', 10, 'I only have 5 minutes', 'I want to do something kind', array['quick', 'easy', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Specific gratitude makes invisible effort feel seen.', 'You send one sincere, specific thank-you message.', 'What effort did you notice that might have gone unseen?', null, false, true),
  ('i_want_to_do_something_kind_i_only_have_5_minutes_2_compliment_the_effort', 'Compliment the Effort', 'Give one person a genuine compliment about their effort, care, consistency, or courage, not their looks or status.', 'Connect', 'Good Sparks', 'Easy', 10, 'I only have 5 minutes', 'I want to do something kind', array['quick', 'easy', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'People are often praised for outcomes, but effort is what they live through.', 'You give one effort-based compliment.', 'What effort became visible once you looked for it?', null, false, true),
  ('i_want_to_do_something_kind_i_only_have_5_minutes_3_leave_one_encouraging_comment', 'Leave One Encouraging Comment', 'Leave a thoughtful comment on someone''s work, post, project, business, art, or achievement.', 'Connect', 'Good Sparks', 'Easy', 10, 'I only have 5 minutes', 'I want to do something kind', array['quick', 'easy', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Most people consume silently. Specific encouragement can become fuel.', 'You leave one specific encouraging comment.', 'What did you genuinely appreciate?', null, false, true),
  ('i_want_to_do_something_kind_i_have_10_15_minutes_1_write_a_helpful_review', 'Write a Helpful Review', 'Write a specific positive review for a local place, creator, freelancer, teacher, app, or service you genuinely value.', 'Connect', 'Good Sparks', 'Easy', 10, 'I have 10-15 minutes', 'I want to do something kind', array['short', 'doable', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'A thoughtful review can help someone earn trust beyond your private appreciation.', 'One specific helpful review is posted or drafted.', 'What deserved public credit?', null, false, true),
  ('i_want_to_do_something_kind_i_have_10_15_minutes_2_remove_one_tiny_burden', 'Remove One Tiny Burden', 'Do one small task that reduces someone else''s load: wash, refill, arrange, pick up, share, remind, or handle something.', 'Connect', 'Good Sparks', 'Easy', 10, 'I have 10-15 minutes', 'I want to do something kind', array['short', 'doable', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Kindness becomes real when it removes friction from someone''s day.', 'One tiny burden is removed for someone else.', 'Whose day did you make slightly easier?', null, false, true),
  ('i_want_to_do_something_kind_i_have_10_15_minutes_3_make_a_warm_introduction', 'Make a Warm Introduction', 'Introduce two people who could genuinely help, encourage, or interest each other, with one sentence of context for each.', 'Connect', 'Good Sparks', 'Easy', 10, 'I have 10-15 minutes', 'I want to do something kind', array['short', 'doable', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Good introductions create possibilities that would not happen alone.', 'One thoughtful introduction is sent.', 'Why might these two people benefit from knowing each other?', null, false, true),
  ('i_want_to_do_something_kind_i_have_15_30_minutes_1_write_a_real_recommendation', 'Write a Real Recommendation', 'Write a short recommendation, testimonial, reference note, or endorsement for someone whose work you trust.', 'Connect', 'Good Sparks', 'Medium', 25, 'I have 15-30 minutes', 'I want to do something kind', array['doable', 'focus', 'meaningful', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Specific public support can open doors for people quietly doing good work.', 'One recommendation, testimonial, or endorsement is written and sent or posted.', 'What strength of theirs deserves to be named?', null, false, true),
  ('i_want_to_do_something_kind_i_have_15_30_minutes_2_help_with_one_practical_thing', 'Help With One Practical Thing', 'Ask someone nearby what would help today, then complete one practical helpful action within your capacity.', 'Connect', 'Good Sparks', 'Medium', 25, 'I have 15-30 minutes', 'I want to do something kind', array['doable', 'focus', 'meaningful', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Kindness lands better when it answers a real need instead of guessing.', 'You ask and complete one practical helpful action.', 'What did they actually need?', null, false, true),
  ('i_want_to_do_something_kind_i_have_15_30_minutes_3_make_a_small_care_delivery', 'Make a Small Care Delivery', 'Prepare or send one small care item: snack, note, resource, link, errand, playlist, or useful information.', 'Connect', 'Good Sparks', 'Medium', 25, 'I have 15-30 minutes', 'I want to do something kind', array['doable', 'focus', 'meaningful', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Small care becomes memorable when it arrives without being demanded.', 'One small care item is prepared, sent, or delivered.', 'What made this care feel personal?', null, false, true),
  ('i_want_to_do_something_kind_i_have_more_than_30_minutes_1_do_a_local_help_block', 'Do a Local Help Block', 'Spend 45 minutes helping a person, neighbor, local group, creator, or small business with a concrete task.', 'Connect', 'Good Sparks', 'Hard', 50, 'I have more than 30 minutes', 'I want to do something kind', array['deep', 'purpose', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Longer kindness blocks create real help, not just a nice intention.', 'One 45-minute concrete help block is completed.', 'What became easier because you showed up?', null, false, true),
  ('i_want_to_do_something_kind_i_have_more_than_30_minutes_2_cook_or_prepare_something_to_share', 'Cook or Prepare Something to Share', 'Make or prepare something simple to share: tea, snack, meal, notes, resource list, playlist, or care kit.', 'Connect', 'Good Sparks', 'Hard', 50, 'I have more than 30 minutes', 'I want to do something kind', array['deep', 'purpose', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Shared effort can make ordinary care feel tangible.', 'One shareable thing is prepared and offered.', 'What felt generous but still realistic?', null, false, true),
  ('i_want_to_do_something_kind_i_have_more_than_30_minutes_3_organize_a_kindness_chain', 'Organize a Kindness Chain', 'Start one small kindness chain by inviting two people to thank, support, review, or help someone specific.', 'Connect', 'Good Sparks', 'Hard', 50, 'I have more than 30 minutes', 'I want to do something kind', array['deep', 'purpose', 'kindness', 'gratitude', 'helpful']::text[], 'Starter', 0, 'Kindness can multiply when the next step is clear and small.', 'Two people are invited into one clear kindness action.', 'Who could use more visible support right now?', null, false, true),
  ('i_want_to_feel_more_present_i_only_have_5_minutes_1_step_outside_and_notice_five_things', 'Step Outside and Notice Five Things', 'Step outside or near a window and name five things you can see, hear, feel, smell, or notice.', 'Reset', 'Fresh Trails', 'Easy', 10, 'I only have 5 minutes', 'I want to feel more present', array['quick', 'easy', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'Presence often returns through the senses before it returns through thoughts.', 'You notice five real-world details.', 'Which detail pulled you into the present?', null, false, true),
  ('i_want_to_feel_more_present_i_only_have_5_minutes_2_observe_one_object_slowly', 'Observe One Object Slowly', 'Pick one ordinary object and study it for two minutes, then describe five details you usually miss.', 'Reset', 'Fresh Trails', 'Easy', 10, 'I only have 5 minutes', 'I want to feel more present', array['quick', 'easy', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'Slowing attention turns ordinary reality back into something noticeable.', 'You describe five details about one object.', 'What had you never noticed before?', null, false, true),
  ('i_want_to_feel_more_present_i_only_have_5_minutes_3_do_a_no_scroll_transition', 'Do a No-Scroll Transition', 'Before switching tasks, spend five minutes doing nothing with your phone away: stand, breathe, sip, or look around.', 'Reset', 'Fresh Trails', 'Easy', 10, 'I only have 5 minutes', 'I want to feel more present', array['quick', 'easy', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'Transitions get swallowed by screens. A pause gives your day edges again.', 'You complete one five-minute no-scroll transition.', 'What did the pause reveal?', null, false, true),
  ('i_want_to_feel_more_present_i_have_10_15_minutes_1_take_a_fresh_route', 'Take a Fresh Route', 'On a walk or errand, take one safe route you do not usually take and notice three details you would normally miss.', 'Reset', 'Fresh Trails', 'Easy', 10, 'I have 10-15 minutes', 'I want to feel more present', array['short', 'doable', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'A small route change interrupts autopilot without needing a big adventure.', 'You take a safe fresh route and notice three real-world details.', 'What detail made the route feel different?', null, false, true),
  ('i_want_to_feel_more_present_i_have_10_15_minutes_2_do_one_chore_fully_present', 'Do One Chore Fully Present', 'Choose one ordinary chore and do it without audio, scrolling, or multitasking, paying attention to the physical steps.', 'Reset', 'Fresh Trails', 'Easy', 10, 'I have 10-15 minutes', 'I want to feel more present', array['short', 'doable', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'A chore can become a reset when it is not treated like background noise.', 'One small chore is completed without digital input.', 'What did the task feel like when it had your full attention?', null, false, true),
  ('i_want_to_feel_more_present_i_have_10_15_minutes_3_make_a_three_photo_reality_check', 'Make a Three-Photo Reality Check', 'Take three photos of real-life details around you that capture today''s texture, not your face or a performance.', 'Reset', 'Fresh Trails', 'Easy', 10, 'I have 10-15 minutes', 'I want to feel more present', array['short', 'doable', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'Noticing real details can pull you out of abstract mental loops.', 'You capture three real-world details.', 'Which photo best represents today?', null, false, true),
  ('i_want_to_feel_more_present_i_have_15_30_minutes_1_sit_somewhere_without_performing', 'Sit Somewhere Without Performing', 'Sit in a public or outdoor place for 20 minutes without posting, scrolling, shopping, or optimizing anything.', 'Reset', 'Fresh Trails', 'Medium', 25, 'I have 15-30 minutes', 'I want to feel more present', array['doable', 'focus', 'meaningful', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'Presence deepens when you are allowed to simply be in a place.', 'You sit for 20 minutes without turning it into content or productivity.', 'What did you notice once you stopped performing?', null, false, true),
  ('i_want_to_feel_more_present_i_have_15_30_minutes_2_do_a_sensory_walk', 'Do a Sensory Walk', 'Walk for 20 minutes and intentionally notice five colors, five sounds, five textures, and one thing changing.', 'Reset', 'Fresh Trails', 'Medium', 25, 'I have 15-30 minutes', 'I want to feel more present', array['doable', 'focus', 'meaningful', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'A sensory walk gives attention a job that is rooted in the real world.', 'You complete the walk and notice the sensory list.', 'Which sense felt most awake?', null, false, true),
  ('i_want_to_feel_more_present_i_have_15_30_minutes_3_have_a_phone_free_meal', 'Have a Phone-Free Meal', 'Eat one meal or snack without your phone, laptop, TV, or reading, even if it is simple.', 'Reset', 'Fresh Trails', 'Medium', 25, 'I have 15-30 minutes', 'I want to feel more present', array['doable', 'focus', 'meaningful', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'Eating without input can make your body feel less like an afterthought.', 'One meal or snack is eaten without digital input.', 'What changed when eating was the only activity?', null, false, true),
  ('i_want_to_feel_more_present_i_have_more_than_30_minutes_1_do_an_offline_morning_block', 'Do an Offline Morning Block', 'Spend the first 45 minutes after waking without social apps, news, or scrolling, and choose one grounded action instead.', 'Reset', 'Fresh Trails', 'Hard', 50, 'I have more than 30 minutes', 'I want to feel more present', array['deep', 'purpose', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'How you enter the day can decide whether your attention belongs to you.', 'One offline morning block is completed or scheduled for tomorrow.', 'What did your attention want before the world entered?', null, false, true),
  ('i_want_to_feel_more_present_i_have_more_than_30_minutes_2_explore_one_nearby_place', 'Explore One Nearby Place', 'Visit a nearby park, street, library, market, temple, cafe, or public place and notice what makes it specific.', 'Reset', 'Fresh Trails', 'Hard', 50, 'I have more than 30 minutes', 'I want to feel more present', array['deep', 'purpose', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'Exploration reminds your brain that life is larger than your usual loop.', 'You visit one nearby place and record three specific observations.', 'What made this place feel alive?', null, false, true),
  ('i_want_to_feel_more_present_i_have_more_than_30_minutes_3_take_a_long_audio_free_walk', 'Take a Long Audio-Free Walk', 'Walk for 40 minutes without music, podcasts, calls, or scrolling, and let your mind settle into the surroundings.', 'Reset', 'Fresh Trails', 'Hard', 50, 'I have more than 30 minutes', 'I want to feel more present', array['deep', 'purpose', 'offline', 'nature', 'movement']::text[], 'Starter', 0, 'A long no-input walk can make the world feel real again.', 'You complete a 40-minute audio-free walk.', 'What appeared once nothing was filling the silence?', null, false, true)

on conflict (mission_id_slug) do update set
  title = excluded.title,
  mission = excluded.mission,
  world = excluded.world,
  category = excluded.category,
  difficulty = excluded.difficulty,
  xp = excluded.xp,
  time_required = excluded.time_required,
  mission_path = excluded.mission_path,
  tags = excluded.tags,
  pack = excluded.pack,
  unlock_xp = excluded.unlock_xp,
  why_it_matters = excluded.why_it_matters,
  completion_condition = excluded.completion_condition,
  reflection_prompt = excluded.reflection_prompt,
  safety_note = excluded.safety_note,
  is_sensitive = excluded.is_sensitive,
  is_active = excluded.is_active;


-- Run after 003a_pulse_columns.sql. Part 4 of 4.
insert into public.missions (
  mission_id_slug,
  title,
  mission,
  world,
  category,
  difficulty,
  xp,
  time_required,
  mission_path,
  tags,
  pack,
  unlock_xp,
  why_it_matters,
  completion_condition,
  reflection_prompt,
  safety_note,
  is_sensitive,
  is_active
)
values
  ('i_want_to_reset_my_life_i_only_have_5_minutes_1_do_a_five_minute_trash_sweep', 'Do a Five-Minute Trash Sweep', 'Set a five-minute timer and remove obvious trash, old cups, wrappers, receipts, or dead clutter from one area.', 'Reset', 'Clear Space', 'Easy', 10, 'I only have 5 minutes', 'I want to reset my life', array['quick', 'easy', 'reset', 'admin', 'focus', 'money']::text[], 'Starter', 0, 'Visible mess often starts with tiny things nobody decided to remove.', 'One area has less visible trash than before.', 'What felt instantly better after the sweep?', null, false, true),
  ('i_want_to_reset_my_life_i_only_have_5_minutes_2_capture_the_loose_ends', 'Capture the Loose Ends', 'Write every loose task in your head into one list without organizing it yet.', 'Reset', 'Clear Space', 'Easy', 10, 'I only have 5 minutes', 'I want to reset my life', array['quick', 'easy', 'reset', 'admin', 'focus', 'money']::text[], 'Starter', 0, 'A captured list is easier to face than a cloud of invisible pressure.', 'Your loose ends are captured in one place.', 'Which loose end had been floating around longest?', null, false, true),
  ('i_want_to_reset_my_life_i_only_have_5_minutes_3_set_tomorrow_s_first_item', 'Set Tomorrow''s First Item', 'Place one item where tomorrow-you will need it: clothes, bag, keys, bottle, notebook, charger, or shoes.', 'Reset', 'Clear Space', 'Easy', 10, 'I only have 5 minutes', 'I want to reset my life', array['quick', 'easy', 'reset', 'admin', 'focus', 'money']::text[], 'Starter', 0, 'Future friction drops when the first step is already visible.', 'One useful item is ready where you will need it.', 'What did you make easier for tomorrow?', null, false, true),
  ('i_want_to_reset_my_life_i_have_10_15_minutes_1_reset_one_friction_spot', 'Reset One Friction Spot', 'Choose one tiny area you touch daily and remove, return, or wipe everything until tomorrow-you can use it without thinking.', 'Reset', 'Clear Space', 'Easy', 10, 'I have 10-15 minutes', 'I want to reset my life', array['short', 'doable', 'reset', 'admin', 'focus', 'money']::text[], 'Starter', 0, 'One small friction spot can create repeated mental drag.', 'One drawer, shelf, bag pocket, desk corner, or bedside surface is visibly reset.', 'What became easier after this tiny reset?', null, false, true),
  ('i_want_to_reset_my_life_i_have_10_15_minutes_2_triage_ten_messages', 'Triage Ten Messages', 'Open one inbox or message app and process exactly ten items: reply, archive, delete, save, or schedule.', 'Reset', 'Clear Space', 'Easy', 10, 'I have 10-15 minutes', 'I want to reset my life', array['short', 'doable', 'reset', 'admin', 'focus', 'money']::text[], 'Starter', 0, 'Small digital piles create avoidable background stress.', 'Ten messages or emails are processed.', 'Which message needed less energy than you expected?', null, false, true),
  ('i_want_to_reset_my_life_i_have_10_15_minutes_3_choose_three_today_priorities', 'Choose Three Today Priorities', 'Write three priorities for the next 24 hours: one must-do, one maintenance task, and one human or health action.', 'Reset', 'Clear Space', 'Easy', 10, 'I have 10-15 minutes', 'I want to reset my life', array['short', 'doable', 'reset', 'admin', 'focus', 'money']::text[], 'Starter', 0, 'A reset starts when the day has fewer competing demands.', 'Three priorities are written for the next 24 hours.', 'Which priority would make the biggest difference?', null, false, true),
  ('i_want_to_reset_my_life_i_have_15_30_minutes_1_audit_one_recurring_charge', 'Audit One Recurring Charge', 'Check your bank, wallet, app store, or email for one recurring charge and cancel, pause, downgrade, or set a dated decision reminder.', 'Reset', 'Clear Space', 'Medium', 25, 'I have 15-30 minutes', 'I want to reset my life', array['doable', 'focus', 'meaningful', 'reset', 'admin', 'money']::text[], 'Starter', 0, 'Recurring charges can quietly drain money and attention when they are never reviewed.', 'One recurring charge is handled or given a dated reminder.', 'How much attention or money did this charge deserve?', null, false, true),
  ('i_want_to_reset_my_life_i_have_15_30_minutes_2_clean_one_digital_folder', 'Clean One Digital Folder', 'Choose one folder, desktop area, notes app, or downloads folder and delete, rename, or move at least 20 items.', 'Reset', 'Clear Space', 'Medium', 25, 'I have 15-30 minutes', 'I want to reset my life', array['doable', 'focus', 'meaningful', 'reset', 'admin', 'money']::text[], 'Starter', 0, 'Digital clutter makes it harder to find your own work and decisions.', 'At least 20 digital items are deleted, renamed, or moved.', 'What did this folder say about what you have been avoiding?', null, false, true),
  ('i_want_to_reset_my_life_i_have_15_30_minutes_3_finish_one_25_minute_block', 'Finish One 25-Minute Block', 'Work for 25 minutes on one important task with distractions closed, then save, send, or write down the visible progress you made.', 'Reset', 'Clear Space', 'Medium', 25, 'I have 15-30 minutes', 'I want to reset my life', array['doable', 'focus', 'meaningful', 'reset', 'admin', 'money']::text[], 'Starter', 0, 'Execution confidence grows when a real block gets completed, not planned.', 'One 25-minute focus block is completed with visible progress captured.', 'What did the focused block move forward?', null, false, true),
  ('i_want_to_reset_my_life_i_have_more_than_30_minutes_1_reset_your_main_workspace', 'Reset Your Main Workspace', 'Spend 45 minutes resetting your main work or study space: clear surfaces, organize tools, remove clutter, and prepare the next task.', 'Reset', 'Clear Space', 'Hard', 50, 'I have more than 30 minutes', 'I want to reset my life', array['deep', 'purpose', 'reset', 'admin', 'focus', 'money']::text[], 'Starter', 0, 'A usable workspace lowers the starting cost of future action.', 'Your main workspace is cleaner and ready for the next task.', 'What will be easier to start now?', null, false, true),
  ('i_want_to_reset_my_life_i_have_more_than_30_minutes_2_do_a_life_admin_hour', 'Do a Life Admin Hour', 'Spend one hour on admin you have delayed: appointments, documents, payments, forms, files, repairs, or scheduling.', 'Reset', 'Clear Space', 'Hard', 50, 'I have more than 30 minutes', 'I want to reset my life', array['deep', 'purpose', 'reset', 'admin', 'focus', 'money']::text[], 'Starter', 0, 'Life admin stops feeling like a monster when it gets a contained hour.', 'One hour of delayed admin is completed with a written progress note.', 'Which admin task lost power once you touched it?', null, false, true),
  ('i_want_to_reset_my_life_i_have_more_than_30_minutes_3_run_a_weekly_reset', 'Run a Weekly Reset', 'Review the next seven days, choose three priorities, clear one space, and prepare one item for tomorrow.', 'Reset', 'Clear Space', 'Hard', 50, 'I have more than 30 minutes', 'I want to reset my life', array['deep', 'purpose', 'reset', 'admin', 'focus', 'money']::text[], 'Starter', 0, 'A weekly reset gives the next few days a calmer starting point.', 'Your week has three priorities, one cleared space, and one prepared item.', 'What does the next week need less of?', null, false, true),
  ('i_want_to_do_something_creative_i_only_have_5_minutes_1_make_a_messy_doodle', 'Make a Messy Doodle', 'Draw, sketch, map, or scribble one messy idea for five minutes without fixing it.', 'Build', 'Spark Lab', 'Easy', 10, 'I only have 5 minutes', 'I want to do something creative', array['quick', 'easy', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'Tiny making breaks the spell of only consuming.', 'One messy visual idea exists on paper or screen.', 'What appeared when you stopped trying to make it good?', null, false, true),
  ('i_want_to_do_something_creative_i_only_have_5_minutes_2_record_a_raw_idea_note', 'Record a Raw Idea Note', 'Record or write a one-minute raw idea note about something you might want to make, say, build, cook, or explore.', 'Build', 'Spark Lab', 'Easy', 10, 'I only have 5 minutes', 'I want to do something creative', array['quick', 'easy', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'A raw idea captured today can become material later.', 'One raw idea note is saved.', 'What part of the idea still has energy?', null, false, true),
  ('i_want_to_do_something_creative_i_only_have_5_minutes_3_title_five_possible_things', 'Title Five Possible Things', 'Write five possible titles for essays, videos, photos, projects, recipes, designs, songs, or posts.', 'Build', 'Spark Lab', 'Easy', 10, 'I only have 5 minutes', 'I want to do something creative', array['quick', 'easy', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'Titles give vague creative energy a handle.', 'Five possible titles are written.', 'Which title wants to become real first?', null, false, true),
  ('i_want_to_do_something_creative_i_have_10_15_minutes_1_make_one_tiny_thing', 'Make One Tiny Thing', 'Create one small thing without judging it: a doodle, note, voice memo, photo, melody, rough paragraph, or layout.', 'Build', 'Spark Lab', 'Easy', 10, 'I have 10-15 minutes', 'I want to do something creative', array['short', 'doable', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'Making something small turns passive time into evidence that you are still in motion.', 'You make one tiny thing and give it a title.', 'What did you make, and what would you call it?', null, false, true),
  ('i_want_to_do_something_creative_i_have_10_15_minutes_2_remix_one_old_idea', 'Remix One Old Idea', 'Find one old note, photo, draft, or idea and turn it into a slightly newer version.', 'Build', 'Spark Lab', 'Easy', 10, 'I have 10-15 minutes', 'I want to do something creative', array['short', 'doable', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'Old ideas often need motion, not a perfect fresh start.', 'One old idea has a new version, angle, or next step.', 'What was still useful in the old idea?', null, false, true),
  ('i_want_to_do_something_creative_i_have_10_15_minutes_3_create_a_tiny_moodboard', 'Create a Tiny Moodboard', 'Collect five images, words, colors, sounds, or references that match the feeling of something you want to make.', 'Build', 'Spark Lab', 'Easy', 10, 'I have 10-15 minutes', 'I want to do something creative', array['short', 'doable', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'Creative direction gets clearer when the feeling becomes visible.', 'A five-piece moodboard or reference list is created.', 'What feeling connects the pieces?', null, false, true),
  ('i_want_to_do_something_creative_i_have_15_30_minutes_1_make_the_rough_first_version', 'Make the Rough First Version', 'Create a rough first version of one idea: sketch, outline, voice note, mockup, recipe test, photo study, or tiny build.', 'Build', 'Spark Lab', 'Medium', 25, 'I have 15-30 minutes', 'I want to do something creative', array['doable', 'focus', 'meaningful', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'A rough version gives your idea a shape you can improve instead of just imagine.', 'You create and save one rough version of an idea.', 'What became clearer once the idea existed outside your head?', null, false, true),
  ('i_want_to_do_something_creative_i_have_15_30_minutes_2_finish_a_tiny_creative_artifact', 'Finish a Tiny Creative Artifact', 'Finish one small creative artifact enough to share, store, or revisit: a page, beat, sketch, edit, recipe, clip, or layout.', 'Build', 'Spark Lab', 'Medium', 25, 'I have 15-30 minutes', 'I want to do something creative', array['doable', 'focus', 'meaningful', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'Completion teaches your creative brain that ideas can land.', 'One tiny artifact is finished to a clear stopping point.', 'What did finishing teach you about the idea?', null, false, true),
  ('i_want_to_do_something_creative_i_have_15_30_minutes_3_practice_one_creative_technique', 'Practice One Creative Technique', 'Choose one technique and practice it for 20 minutes: line work, editing, lighting, rhythm, color, writing, camera, or layout.', 'Build', 'Spark Lab', 'Medium', 25, 'I have 15-30 minutes', 'I want to do something creative', array['doable', 'focus', 'meaningful', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'Skill grows when practice has one clear target.', 'One creative technique is practiced for 20 minutes.', 'What improved even slightly?', null, false, true),
  ('i_want_to_do_something_creative_i_have_more_than_30_minutes_1_do_a_deep_creative_block', 'Do a Deep Creative Block', 'Spend 60 minutes making one thing with notifications off and a clear finish line for the session.', 'Build', 'Spark Lab', 'Hard', 50, 'I have more than 30 minutes', 'I want to do something creative', array['deep', 'purpose', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'Longer creative work needs protected time more than inspiration.', 'One 60-minute creative block is completed with a saved output.', 'What did the protected block make possible?', null, false, true),
  ('i_want_to_do_something_creative_i_have_more_than_30_minutes_2_build_a_shareable_mini_piece', 'Build a Shareable Mini Piece', 'Create a small piece you could show someone: a short post, photo set, recipe, design, demo, poem, page, or recording.', 'Build', 'Spark Lab', 'Hard', 50, 'I have more than 30 minutes', 'I want to do something creative', array['deep', 'purpose', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'Shareable does not mean perfect. It means the idea has left your head.', 'One mini piece is created and ready to show or store.', 'What would you improve next, not before sharing?', null, false, true),
  ('i_want_to_do_something_creative_i_have_more_than_30_minutes_3_take_a_creative_field_trip', 'Take a Creative Field Trip', 'Go somewhere that can feed your creativity: market, street, library, gallery, park, bookstore, cafe, or hardware store, and collect five references.', 'Build', 'Spark Lab', 'Hard', 50, 'I have more than 30 minutes', 'I want to do something creative', array['deep', 'purpose', 'creative', 'expression', 'craft']::text[], 'Starter', 0, 'New input from the real world gives creativity better raw material.', 'You visit one place and collect five creative references.', 'What did the place give you that your room could not?', null, false, true)

on conflict (mission_id_slug) do update set
  title = excluded.title,
  mission = excluded.mission,
  world = excluded.world,
  category = excluded.category,
  difficulty = excluded.difficulty,
  xp = excluded.xp,
  time_required = excluded.time_required,
  mission_path = excluded.mission_path,
  tags = excluded.tags,
  pack = excluded.pack,
  unlock_xp = excluded.unlock_xp,
  why_it_matters = excluded.why_it_matters,
  completion_condition = excluded.completion_condition,
  reflection_prompt = excluded.reflection_prompt,
  safety_note = excluded.safety_note,
  is_sensitive = excluded.is_sensitive,
  is_active = excluded.is_active;


select
  count(*) as active_pulses,
  count(*) filter (where mission_path is not null) as pulses_with_paths
from public.missions
where is_active = true;
